### ISSUE TITLE
No Deprecation for passes.Legalize https://github.com/chipsalliance/firrtl/pull/2304

### ISSUE THREAD

**Issue by mwachs5** [chipsalliance/firrtl#2345]
### Checklist

- [ ] Did you specify the current behavior?
- [ ] Did you specify the expected behavior?
- [ ] Did you provide a code example showing the problem?
- [ ] Did you describe your environment?
- [ ] Did you specify relevant external information?

### What is the current behavior?

If I take code (barstools) that was working on Chisel 3.4 and try to run it on Chisel 3.5, I get an error about 
```
barstools/macros/src/main/scala/barstools/macros/MacroCompiler.scala:786: object Legalize is not a member of package firrtl.passes
```

Apparently this was never deprecated, it was just renamed and moved to:

firrtl.backends.verilog.LegalizeVerilog

### What is the expected behavior?

I should have gotten a deprecation warning on my 3.4 branch so it was clearer how to fix when moving to 3.5.

### Steps to Reproduce

Have chisel 3.4 code that uses `firrtl.passes.Legalize`... then update past this commit: https://github.com/chipsalliance/firrtl/pull/2304

### Your environment

- Chisel Verions: `master`
- OS: 
- Verilator version:
